### ISSUE TITLE
Problem using EPCwrite

### ISSUE THREAD

**Issue by ombi** [sparkfun/SparkFun_Simultaneous_RFID_Tag_Reader_Library#17]
I try to write (update) a Epc tag, apparentely it works but the when a read the tag again even if it is changed is done not in the way  I expect. For example if  I write, "Hello!",reading again the same tag its EPC  doesn't contain any of the bytes of the orginal string, even if it appears different from the evalue read before the write....

**Comment by ombi** [comment]
I fixed the problem that was generated by the last release of the library.  It introduces an incorrect atoi function at line 276.  The use of the atoi function on the twelve byte of EPC make no sense as it is a binary sequence.  As soon as the function is removed, it starts working properly again.

**Comment by nseidle** [comment]
Hi Ombi - Thank you for reporting the error and fix. I apologize, it went unnoticed until today because you closed the issue. I really appreciate your help tho. In the future, please keep issues open (until I can get them fixed :) ) or if you can create a PR then I'll be *really* ecstatic.

All the best,
-Nathan

**Comment by nseidle** [comment]
Bug should be fixed in latest library release v1.0.7.
