### ISSUE TITLE
Trying to do a constant read with the SparkFun M6E Nano and a Raspberry Pico

### ISSUE THREAD

**Issue by razaula** [sparkfun/SparkFun_Simultaneous_RFID_Tag_Reader_Library#30]
Has anyone tried to connect the SparkFun M6E Nano with a Raspberry Pico using the Arduino IDE? I am trying to run the constant read example. I used the Software Serial example, and it fails to connect and goes to "Please check wiring" error. I'm not sure if I have any better luck using the hardware serial example instead. If someone has tried it. How were you guys able to fix it?

**Comment by sfe-SparkFro** [comment]
Hi there! I just tested this on a Pico W, and it appears to work with the hardware serial example (haven't tested software serial, but hardware is arguably better anyways). Just need to make sure you specify the correct UART bus and pins for your project:

Take a look at the Function Select table of the [RP2040 datasheet](https://datasheets.raspberrypi.com/rp2040/rp2040-datasheet.pdf) (Table 278, page 237 as of writing). The F2 column specifies which pins and UART bus can be used with each pin (only some pins support TX and RX). Assuming you're using [Earle Philhower's arduino-pico core](https://github.com/earlephilhower/arduino-pico), UART0 and UART1 correspond to `Serial1` and `Serial2` respectively.

So to get it working, first figure out which pins you want to use. Then open the hardware serial example (under the Advanced folder) and replace all instances of `Serial5` with `Serial1` or `Serial2` (depending on which pins you're using, I'm just going to call it `SerialN` for here on). Then before `SerialN.begin()` (line 118), add `SerialN.setTX()` and `SerialN.setRX()`, and pass in the pin numbers you want to use.

For example, I used pins 20 and 21 for my TX and RX respectively, which support UART1, or `Serial2`. So I replaced all instances of `Serial5` with `Serial2`, and added the following

```
...

Serial2.setTX(20);
Serial2.setRX(21);

Serial2.begin(baudRate);

...
```

I hope this helps! Going to close this since it doesn't appear to be an issue with this library. Please feel free to reply if you're still having trouble, or reopen if you believe there really is a problem with this library. Thank you!
